### PR TITLE
Hey! I made a rockspec for you.

### PR DESCRIPTION
**Pull request by DorianGray**
Feel free to modify any of the content. If you could also upload a source tarball that would be awesome. We're using your library in busted! https://github.com/Olivine-Labs/busted

### CODE REVIEW

**Comment by kikito** [comment]
Thanks a lot!

I confess I am not familiar with the whole luarocks approval process, I did it only once in the past and I have not repeated ever since. Must I send an email to their mailing list, or is there a better procedure?

By the way, your library looks ... beautiful! I'm loving what I'm seeing. I hope it gets mainstream. I will give it some publicity, that's for sure.

**Comment by kikito** [comment]
Re: the source tarball, isn't it enough with the ones that github generates for each tag?

https://github.com/kikito/ansicolors.lua/tags

**Comment by DorianGray** [comment]
Unfortunately, LuaRocks has trouble determining the mime type of github tarballs, you need to upload a source tarball as a separate download with a .tar.gz file extension. I'm going to make a pull request to them as well when I get time to fix that.

**Comment by DorianGray** [comment]
Also, thank you! I hope it does too =)

**Comment by DorianGray** [comment]
And...it's still through the mailing list. Also, for the tarball, check the luarock and name it accordinly when you upload. ansicolors-1.0.tar.gz

**Comment by kikito** [comment]
Did the upload. Sorry about the time it took me, I am currently on holidays and AWK most of the time. Cheers!

**Pull request merged**
